In [1]:
using MarketData

INFO: Precompiling module MarketData.


In [3]:
AAPL

8336x12 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 2013-12-31

             Open      High      Low       Close     Volume          Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume     
1980-12-12 | 28.75     28.88     28.75     28.75     2093900         0.0          1            3.3766     3.3919     3.3766    3.3766      16751200        
1980-12-15 | 27.38     27.38     27.25     27.25     785200          0.0          1            3.2157     3.2157     3.2004    3.2004      6281600         
1980-12-16 | 25.38     25.38     25.25     25.25     472000          0.0          1            2.9808     2.9808     2.9655    2.9655      3776000         
1980-12-17 | 25.88     26.0      25.88     25.88     385900          0.0          1            3.0395     3.0536     3.0395    3.0395      3087200         
⋮
2013-12-26 | 568.1     569.5     563.38    563.9     7286000         0.0          1            564.7392   566.1309   560.0471  560

In [4]:
?AAPL

search: AAPL DataType airyaiprime asyncmap unsafe_wrap AbstractSparseArray



No documentation found.

`MarketData.AAPL` is of type `TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}}`.

**Summary:**

```
immutable TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} <: TimeSeries.AbstractTimeSeries
```

**Fields:**

```
timestamp :: Array{Date,1}
values    :: Array{Float64,2}
colnames  :: Array{String,1}
meta      :: Any
```


In [5]:
?TimeSeries

search:



No documentation found.

Displaying the `README.md` for the module instead.

---

# TimeSeries.jl

[![Build Status](https://travis-ci.org/JuliaStats/TimeSeries.jl.svg?branch=master)](https://travis-ci.org/JuliaStats/TimeSeries.jl) [![Coverage Status](https://coveralls.io/repos/JuliaStats/TimeSeries.jl/badge.svg?branch=master)](https://coveralls.io/r/JuliaStats/TimeSeries.jl?branch=master) [![TimeSeries](http://pkg.julialang.org/badges/TimeSeries_0.4.svg)](http://pkg.julialang.org/?pkg=TimeSeries&ver=0.4) [![TimeSeries](http://pkg.julialang.org/badges/TimeSeries_0.5.svg)](http://pkg.julialang.org/?pkg=TimeSeries&ver=0.5) [![Documentation Status](https://readthedocs.org/projects/timeseriesjl/badge/?version=latest)](http://timeseriesjl.readthedocs.io/en/latest/?badge=latest)

TimeSeries aims to provide a lightweight framework for working with time series data in Julia. Documentation is provided  [here](http://timeseriesjl.readthedocs.org/en/latest/).


In [6]:
show(AAPL)

8336x12 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 2013-12-31

             Open      High      Low       Close     Volume          Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume     
1980-12-12 | 28.75     28.88     28.75     28.75     2093900         0.0          1            3.3766     3.3919     3.3766    3.3766      16751200        
1980-12-15 | 27.38     27.38     27.25     27.25     785200          0.0          1            3.2157     3.2157     3.2004    3.2004      6281600         
1980-12-16 | 25.38     25.38     25.25     25.25     472000          0.0          1            2.9808     2.9808     2.9655    2.9655      3776000         
1980-12-17 | 25.88     26.0      25.88     25.88     385900          0.0          1            3.0395     3.0536     3.0395    3.0395      3087200         
⋮
2013-12-26 | 568.1     569.5     563.38    563.9     7286000         0.0          1            564.7392   566.1309   560.0471  560

In [7]:
ohlc = AAPL

8336x12 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 2013-12-31

             Open      High      Low       Close     Volume          Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume     
1980-12-12 | 28.75     28.88     28.75     28.75     2093900         0.0          1            3.3766     3.3919     3.3766    3.3766      16751200        
1980-12-15 | 27.38     27.38     27.25     27.25     785200          0.0          1            3.2157     3.2157     3.2004    3.2004      6281600         
1980-12-16 | 25.38     25.38     25.25     25.25     472000          0.0          1            2.9808     2.9808     2.9655    2.9655      3776000         
1980-12-17 | 25.88     26.0      25.88     25.88     385900          0.0          1            3.0395     3.0536     3.0395    3.0395      3087200         
⋮
2013-12-26 | 568.1     569.5     563.38    563.9     7286000         0.0          1            564.7392   566.1309   560.0471  560

In [8]:
ohlc[1]

1x12 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 1980-12-12

             Open     High     Low      Close    Volume        Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume    
1980-12-12 | 28.75    28.88    28.75    28.75    2093900       0            1            3.3766     3.3919     3.3766    3.3766      16751200       


In [9]:
ohlc[1:3]

3x12 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 1980-12-16

             Open     High     Low      Close    Volume        Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume    
1980-12-12 | 28.75    28.88    28.75    28.75    2093900       0            1            3.3766     3.3919     3.3766    3.3766      16751200       
1980-12-15 | 27.38    27.38    27.25    27.25    785200        0            1            3.2157     3.2157     3.2004    3.2004      6281600        
1980-12-16 | 25.38    25.38    25.25    25.25    472000        0            1            2.9808     2.9808     2.9655    2.9655      3776000        


In [13]:
ohlc[[1:3; 8]]

4x12 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 1980-12-23

             Open     High     Low      Close    Volume        Ex-Dividend  Split Ratio  Adj. Open  Adj. High  Adj. Low  Adj. Close  Adj. Volume    
1980-12-12 | 28.75    28.88    28.75    28.75    2093900       0            1            3.3766     3.3919     3.3766    3.3766      16751200       
1980-12-15 | 27.38    27.38    27.25    27.25    785200        0            1            3.2157     3.2157     3.2004    3.2004      6281600        
1980-12-16 | 25.38    25.38    25.25    25.25    472000        0            1            2.9808     2.9808     2.9655    2.9655      3776000        
1980-12-23 | 30.88    31.0     30.88    30.88    209600        0            1            3.6267     3.6408     3.6267    3.6267      1676800        


In [14]:
ohlc["Open"]

8336x1 TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}} 1980-12-12 to 2013-12-31

             Open      
1980-12-12 | 28.75     
1980-12-15 | 27.38     
1980-12-16 | 25.38     
1980-12-17 | 25.88     
⋮
2013-12-26 | 568.1     
2013-12-27 | 563.82    
2013-12-30 | 557.46    
2013-12-31 | 554.17    


In [16]:
ohlc = AAPL["Open", "High", "Low", "Close"]

8336x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-12 to 2013-12-31

             Open      High      Low       Close     
1980-12-12 | 28.75     28.88     28.75     28.75     
1980-12-15 | 27.38     27.38     27.25     27.25     
1980-12-16 | 25.38     25.38     25.25     25.25     
1980-12-17 | 25.88     26.0      25.88     25.88     
⋮
2013-12-26 | 568.1     569.5     563.38    563.9     
2013-12-27 | 563.82    564.41    559.5     560.09    
2013-12-30 | 557.46    560.09    552.32    554.52    
2013-12-31 | 554.17    561.28    554.0     561.02    


In [18]:
ohlc[Date(2000,1,3)]

1x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 2000-01-03 to 2000-01-03

             Open      High      Low       Close     
2000-01-03 | 104.88    112.5     101.69    111.94    


In [19]:
ohlc[[Date(2000,1,3),Date(2000,2,4)]]

2x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 2000-01-03 to 2000-02-04

             Open      High      Low       Close     
2000-01-03 | 104.88    112.5     101.69    111.94    
2000-02-04 | 103.94    110.0     103.62    108.0     


In [20]:
ohlc[Date(2000,1,3):Date(2000,2,4)]

24x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 2000-01-03 to 2000-02-04

             Open      High      Low       Close     
2000-01-03 | 104.88    112.5     101.69    111.94    
2000-01-04 | 108.25    110.62    101.19    102.5     
2000-01-05 | 103.75    110.56    103.0     104.0     
2000-01-06 | 106.12    107.0     95.0      95.0      
⋮
2000-02-01 | 104.0     105.0     100.0     100.25    
2000-02-02 | 100.75    102.12    97.0      98.81     
2000-02-03 | 100.31    104.25    100.25    103.31    
2000-02-04 | 103.94    110.0     103.62    108.0     


In [23]:
ohlc[Date(2000, 1, 1):Date(2000, 1, 31)]

20x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 2000-01-03 to 2000-01-31

             Open      High      Low       Close     
2000-01-03 | 104.88    112.5     101.69    111.94    
2000-01-04 | 108.25    110.62    101.19    102.5     
2000-01-05 | 103.75    110.56    103.0     104.0     
2000-01-06 | 106.12    107.0     95.0      95.0      
⋮
2000-01-26 | 110.0     114.19    109.75    110.19    
2000-01-27 | 108.81    113.0     107.0     110.0     
2000-01-28 | 108.19    110.88    100.62    101.62    
2000-01-31 | 101.0     103.88    94.5      103.75    


In [24]:
ohlc["Open"][1:3]

3x1 TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}} 1980-12-12 to 1980-12-16

             Open     
1980-12-12 | 28.75    
1980-12-15 | 27.38    
1980-12-16 | 25.38    


In [29]:
when(ohlc, dayofweek, 1)

1580x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-15 to 2013-12-30

             Open      High      Low       Close     
1980-12-15 | 27.38     27.38     27.25     27.25     
1980-12-22 | 29.62     29.75     29.62     29.62     
1980-12-29 | 36.0      36.12     36.0      36.0      
1981-01-05 | 33.88     33.88     33.75     33.75     
⋮
2013-12-09 | 560.9     569.58    560.9     566.43    
2013-12-16 | 555.02    562.64    555.01    557.5     
2013-12-23 | 568.0     570.72    562.76    570.09    
2013-12-30 | 557.46    560.09    552.32    554.52    


In [28]:
using TimeSeries

In [31]:
when(ohlc, dayname, "Tuesday")

1708x4 TimeSeries.TimeArray{Float64,2,Date,Array{Float64,2}} 1980-12-16 to 2013-12-31

             Open      High      Low       Close     
1980-12-16 | 25.38     25.38     25.25     25.25     
1980-12-23 | 30.88     31.0      30.88     30.88     
1980-12-30 | 35.25     35.25     35.12     35.12     
1981-01-06 | 32.38     32.38     32.25     32.25     
⋮
2013-12-10 | 563.58    567.88    561.2     565.55    
2013-12-17 | 555.81    559.44    553.38    554.99    
2013-12-24 | 569.89    571.88    566.03    567.67    
2013-12-31 | 554.17    561.28    554.0     561.02    


In [33]:
from(cl, Date(2001, 12, 27))

3x1 TimeSeries.TimeArray{Float64,1,Date,Array{Float64,1}} 2001-12-27 to 2001-12-31

             Close    
2001-12-27 | 22.07    
2001-12-28 | 22.43    
2001-12-31 | 21.9     


In [35]:
green = findwhen(ohlc["Close"] .> ohlc["Open"])
green

3636-element Array{Date,1}:
 1982-10-04
 1982-10-05
 1982-10-06
 1982-10-07
 1982-10-08
 1982-10-11
 1982-10-13
 1982-10-14
 1982-10-18
 1982-10-19
 1982-10-20
 1982-10-21
 1982-10-26
 ⋮         
 2013-11-25
 2013-11-26
 2013-11-27
 2013-11-29
 2013-12-03
 2013-12-09
 2013-12-10
 2013-12-16
 2013-12-18
 2013-12-20
 2013-12-23
 2013-12-31

In [39]:
typeof(ohlc["Close"] .> ohlc["Open"])

TimeSeries.TimeArray{Bool,1,Date,BitArray{1}}

In [37]:
?find

search: find findn findnz findin findmin findmax findall findprev findnext



```
find(f::Function, A)
```

Return a vector `I` of the linear indexes of `A` where `f(A[I])` returns `true`. If there are no such elements of `A`, find returns an empty array.

```jldoctest
julia> A = [1 2; 3 4]
2×2 Array{Int64,2}:
 1  2
 3  4

julia> find(isodd,A)
2-element Array{Int64,1}:
 1
 2
```

```
find(A)
```

Return a vector of the linear indexes of the non-zeros in `A` (determined by `A[i]!=0`). A common use of this is to convert a boolean array to an array of indexes of the `true` elements. If there are no non-zero elements of `A`, `find` returns an empty array.

```jldoctest
julia> A = [true false; false true]
2×2 Array{Bool,2}:
  true  false
 false   true

julia> find(A)
2-element Array{Int64,1}:
 1
 4
```


In [40]:
?head

search: head Threads @threadcall blas_set_num_threads hessfact hessfact!



No documentation found.

`TimeSeries.head` is a `Function`.

```
# 2 methods for generic function "head":
head{T,N,D}(ta::TimeSeries.TimeArray{T,N,D,A<:AbstractArray}) at C:\Users\ChuKY\.julia\v0.5\TimeSeries\src\split.jl:33
head{T,N,D}(ta::TimeSeries.TimeArray{T,N,D,A<:AbstractArray}, n::Int64) at C:\Users\ChuKY\.julia\v0.5\TimeSeries\src\split.jl:33
```


In [41]:
?update

search: update



No documentation found.

`TimeSeries.update` is a `Function`.

```
# 2 methods for generic function "update":
update{T,N,D}(ta::TimeSeries.TimeArray{T,N,D,A<:AbstractArray}, tstamp::D, val::Array{T,N}) at C:\Users\ChuKY\.julia\v0.5\TimeSeries\src\modify.jl:5
update{T,N,D}(ta::TimeSeries.TimeArray{T,N,D,A<:AbstractArray}, tstamp::D, val::T) at C:\Users\ChuKY\.julia\v0.5\TimeSeries\src\modify.jl:19
```
